export const arr = [
    {
        id: 246016548,
        title: 'Навигационная система Soundmax',
        category: 'Техника для дома',
        units: 'шт',
        count: 5,
        price: 60000,
    },
    {
        id: 937295527,
        title: 'Настольная игра “На 4-х ногах”',
        category: 'Настольные игры',
        units: 'шт',
        count: 12,
        price: 840,
    },
    {
        id: 253842678,
        title: 'Смартфон Xiaomi 11T 8/128GB',
        category: 'mobile-phone',
        units: 'шт',
        count: 3,
        price: 27000,
    },
    {
        id: 296378448,
        title: 'Радиоуправляемый автомобиль Cheetan',
        category: 'toys',
        units: 'шт',
        count: 1,
        price: 4000,
    },
    {
        id: 215796548,
        title: 'ТВ приставка MECOOL KI',
        category: 'tv-box',
        units: 'шт',
        count: 4,
        price: 12400,
    },
    {
        id: 246258248,
        title: 'Витая пара PROConnect 01-0043-3-25',
        category: 'cables',
        units: 'шт',
        count: 420,
        price: 22,
    },
];
